# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20160618_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='introduction',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
