# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
