# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
