# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinesename', models.CharField(max_length=20)),
                ('englishname', models.CharField(max_length=20)),
                ('schoolid', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=200)),
            ],
        ),
    ]
